package com.smartchain.security;

public enum Permission {
    FINANCE_WRITE,
    FINANCE_READ,
    ACCOUNTING_CLOSE,
    INVENTORY_WRITE,
    PROCUREMENT_WRITE,
    SALES_WRITE,
    HR_READ,
    HR_WRITE,
    ASSET_READ,
    ASSET_WRITE,
    DOCUMENT_WRITE,
    DOCUMENT_READ,
    ADMIN_TENANT_WRITE,
    ADMIN_SECURITY_WRITE,
    FEATURE_FLAG_WRITE,
    PROJECTION_REBUILD
}
