import {appSchema, tableSchema} from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 7,
  tables: [
    tableSchema({
      name: 'offline_transactions',
      columns: [
        {name: 'operation_type', type: 'string'},
        {name: 'payload', type: 'string'},
        {name: 'idempotency_key', type: 'string'},
        {name: 'saved_at', type: 'string'},
        {name: 'synced', type: 'boolean'},
        {name: 'retry_count', type: 'number'},
        {name: 'last_error', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'pending_receipts',
      columns: [
        {name: 'transaction_id', type: 'string'},
        {name: 'receipt_data', type: 'string'},
        {name: 'printed', type: 'boolean'},
        {name: 'saved_at', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'uoms',
      columns: [
        {name: 'name', type: 'string'},
        {name: 'conversion_factor', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'suppliers',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'phone', type: 'string', isOptional: true},
        {name: 'email', type: 'string', isOptional: true},
        {name: 'address', type: 'string', isOptional: true},
        {name: 'tin_number', type: 'string', isOptional: true},
        {name: 'notes', type: 'string', isOptional: true},
        {name: 'deleted_at', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'sku', type: 'string'},
        {name: 'preferred_supplier_id', type: 'string', isOptional: true},
        {name: 'purchase_uom_id', type: 'string', isOptional: true},
        {name: 'sale_uom_id', type: 'string', isOptional: true},
        {name: 'uom_conversion_factor', type: 'number'},
        {name: 'reorder_point', type: 'number'},
        {name: 'reorder_qty', type: 'number'},
        {name: 'is_serial_tracked', type: 'boolean'},
        {name: 'base_unit_price', type: 'number'},
        {name: 'currency_code', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'product_variants',
      columns: [
        {name: 'product_id', type: 'string', isIndexed: true},
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'sku', type: 'string'},
        {name: 'name', type: 'string'},
        {name: 'attributes_json', type: 'string'},
        {name: 'barcode', type: 'string', isIndexed: true},
        {name: 'price_override', type: 'number', isOptional: true},
        {name: 'stock_qty', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'variant_batches',
      columns: [
        {name: 'variant_id', type: 'string', isIndexed: true},
        {name: 'product_id', type: 'string', isIndexed: true},
        {name: 'batch_number', type: 'string'},
        {name: 'qty', type: 'number'},
        {name: 'expiry_date', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'serial_numbers',
      columns: [
        {name: 'variant_id', type: 'string', isIndexed: true},
        {name: 'product_id', type: 'string', isIndexed: true},
        {name: 'serial', type: 'string', isIndexed: true},
        {name: 'status', type: 'string'},
        {name: 'sale_id', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'purchase_orders',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'supplier_id', type: 'string'},
        {name: 'status', type: 'string'},
        {name: 'created_by', type: 'string', isOptional: true},
        {name: 'ordered_at', type: 'string'},
        {name: 'expected_delivery_date', type: 'string', isOptional: true},
        {name: 'notes', type: 'string', isOptional: true},
        {name: 'needs_sync', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'purchase_order_lines',
      columns: [
        {name: 'po_id', type: 'string', isIndexed: true},
        {name: 'product_id', type: 'string'},
        {name: 'variant_id', type: 'string', isOptional: true},
        {name: 'server_product_id', type: 'string', isOptional: true},
        {name: 'ordered_qty', type: 'number'},
        {name: 'uom_id', type: 'string', isOptional: true},
        {name: 'unit_cost', type: 'number'},
        {name: 'received_qty', type: 'number'},
        {name: 'sku', type: 'string'},
        {name: 'product_name', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'grns',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'po_id', type: 'string', isOptional: true},
        {name: 'supplier_id', type: 'string'},
        {name: 'received_by', type: 'string', isOptional: true},
        {name: 'received_at', type: 'string'},
        {name: 'status', type: 'string'},
        {name: 'notes', type: 'string', isOptional: true},
        {name: 'needs_sync', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'grn_lines',
      columns: [
        {name: 'grn_id', type: 'string', isIndexed: true},
        {name: 'product_id', type: 'string'},
        {name: 'variant_id', type: 'string', isOptional: true},
        {name: 'qty_received', type: 'number'},
        {name: 'unit_cost', type: 'number'},
        {name: 'expiry_date', type: 'string', isOptional: true},
        {name: 'batch_number', type: 'string', isOptional: true},
        {name: 'serial_numbers_json', type: 'string', isOptional: true},
        {name: 'sku', type: 'string'},
        {name: 'product_name', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'phone', type: 'string', isOptional: true},
        {name: 'email', type: 'string', isOptional: true},
        {name: 'tin_number', type: 'string', isOptional: true},
        {name: 'customer_type', type: 'string'},
        {name: 'price_list_id', type: 'string', isOptional: true},
        {name: 'credit_limit', type: 'number'},
        {name: 'credit_balance', type: 'number'},
        {name: 'loyalty_points', type: 'number'},
        {name: 'loyalty_enabled', type: 'boolean'},
        {name: 'tax_exempt', type: 'boolean'},
        {name: 'notes', type: 'string', isOptional: true},
        {name: 'deleted_at', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'price_lists',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'currency_code', type: 'string'},
        {name: 'discount_pct', type: 'number', isOptional: true},
        {name: 'valid_from', type: 'string', isOptional: true},
        {name: 'valid_to', type: 'string', isOptional: true},
        {name: 'deleted_at', type: 'string', isOptional: true},
        {name: 'location_id', type: 'string', isOptional: true},
        {name: 'scope', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'locations',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'location_code', type: 'string'},
        {name: 'currency_default', type: 'string', isOptional: true},
        {name: 'is_active', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'registers',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'location_id', type: 'string', isIndexed: true},
        {name: 'name', type: 'string'},
        {name: 'hardware_id', type: 'string', isOptional: true},
        {name: 'is_active', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'price_list_lines',
      columns: [
        {name: 'price_list_id', type: 'string', isIndexed: true},
        {name: 'product_id', type: 'string'},
        {name: 'variant_id', type: 'string', isOptional: true},
        {name: 'unit_price', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'promotions_cache',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'name', type: 'string'},
        {name: 'promotion_type', type: 'string'},
        {name: 'discount_value', type: 'number', isOptional: true},
        {name: 'bundle_price', type: 'number', isOptional: true},
        {name: 'buy_quantity', type: 'number', isOptional: true},
        {name: 'get_quantity', type: 'number', isOptional: true},
        {name: 'minimum_purchase', type: 'number', isOptional: true},
        {name: 'maximum_discount', type: 'number', isOptional: true},
        {name: 'applies_to', type: 'string', isOptional: true},
        {name: 'product_ids_json', type: 'string', isOptional: true},
        {name: 'active', type: 'boolean'},
        {name: 'valid_from', type: 'string', isOptional: true},
        {name: 'valid_to', type: 'string', isOptional: true},
        {name: 'allow_stack', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'layaway_orders',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'customer_id', type: 'string'},
        {name: 'status', type: 'string'},
        {name: 'currency_code', type: 'string'},
        {name: 'total_amount', type: 'number'},
        {name: 'deposit_amount', type: 'number'},
        {name: 'balance_due', type: 'number'},
        {name: 'collection_date', type: 'string', isOptional: true},
        {name: 'cart_json', type: 'string'},
        {name: 'needs_sync', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'sales_quotes',
      columns: [
        {name: 'server_id', type: 'string', isOptional: true},
        {name: 'customer_id', type: 'string', isOptional: true},
        {name: 'status', type: 'string'},
        {name: 'currency_code', type: 'string'},
        {name: 'total_amount', type: 'number'},
        {name: 'expiry_date', type: 'string', isOptional: true},
        {name: 'cart_json', type: 'string'},
        {name: 'needs_sync', type: 'boolean'},
      ],
    }),
    tableSchema({
      name: 'efd_submissions',
      columns: [
        {name: 'sales_order_id', type: 'string', isIndexed: true},
        {name: 'payload_json', type: 'string'},
        {name: 'status', type: 'string'},
        {name: 'fiscal_signature', type: 'string', isOptional: true},
        {name: 'fiscal_qr_data', type: 'string', isOptional: true},
        {name: 'retry_count', type: 'number'},
        {name: 'last_error', type: 'string', isOptional: true},
        {name: 'saved_at', type: 'string'},
        {name: 'confirmed_at', type: 'string', isOptional: true},
      ],
    }),
    tableSchema({
      name: 'fiscal_audit_log',
      columns: [
        {name: 'entity_type', type: 'string'},
        {name: 'entity_id', type: 'string'},
        {name: 'action', type: 'string'},
        {name: 'actor_id', type: 'string'},
        {name: 'timestamp', type: 'string'},
        {name: 'previous_hash', type: 'string'},
        {name: 'hash', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'z_reports_local',
      columns: [
        {name: 'till_session_id', type: 'string', isIndexed: true},
        {name: 'report_type', type: 'string'},
        {name: 'payload_json', type: 'string'},
        {name: 'reprint_locked', type: 'boolean'},
        {name: 'saved_at', type: 'string'},
      ],
    }),
    tableSchema({
      name: 'receipt_configs_local',
      columns: [
        {name: 'business_name', type: 'string'},
        {name: 'business_tin', type: 'string'},
        {name: 'logo_base64', type: 'string', isOptional: true},
        {name: 'footer_text', type: 'string'},
        {name: 'show_vat_breakdown', type: 'boolean'},
        {name: 'paper_width_mm', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'tax_configs_cache',
      columns: [
        {name: 'server_id', type: 'string'},
        {name: 'name', type: 'string'},
        {name: 'rate', type: 'number'},
        {name: 'type', type: 'string'},
        {name: 'applies_to', type: 'string'},
        {name: 'category_code', type: 'string', isOptional: true},
        {name: 'is_active', type: 'boolean'},
      ],
    }),
  ],
});
