-- Idempotent permission catalog (28 codes). Uses `label` column per V73 schema.
INSERT INTO permissions (id, code, label, category) VALUES
    (gen_random_uuid(), 'POS_ACCESS',          'POS Access',          'POS'),
    (gen_random_uuid(), 'POS_TILL_MANAGE',     'Till Management',     'POS'),
    (gen_random_uuid(), 'POS_RETURNS',         'Process Returns',     'POS'),
    (gen_random_uuid(), 'POS_DISCOUNT',        'Apply Discounts',     'POS'),
    (gen_random_uuid(), 'EBM_SUBMIT',          'Submit to EBM',       'EBM'),
    (gen_random_uuid(), 'EBM_CONFIG',          'EBM Configuration',   'EBM'),
    (gen_random_uuid(), 'EBM_AUDIT',           'EBM Audit Log',       'EBM'),
    (gen_random_uuid(), 'INVENTORY_READ',      'View Inventory',      'INVENTORY'),
    (gen_random_uuid(), 'INVENTORY_WRITE',     'Edit Inventory',      'INVENTORY'),
    (gen_random_uuid(), 'INVENTORY_SHRINKAGE', 'Record Shrinkage',    'INVENTORY'),
    (gen_random_uuid(), 'PROCUREMENT_READ',    'View Procurement',    'PROCUREMENT'),
    (gen_random_uuid(), 'PROCUREMENT_WRITE',   'Edit Procurement',    'PROCUREMENT'),
    (gen_random_uuid(), 'FINANCE_READ',        'View Finances',       'FINANCE'),
    (gen_random_uuid(), 'FINANCE_WRITE',       'Edit Finances',       'FINANCE'),
    (gen_random_uuid(), 'FINANCE_CLOSE',       'Close Period',        'FINANCE'),
    (gen_random_uuid(), 'PAYROLL_READ',        'View Payroll',        'PAYROLL'),
    (gen_random_uuid(), 'PAYROLL_WRITE',       'Approve Payroll',     'PAYROLL'),
    (gen_random_uuid(), 'HR_READ',             'View HR',             'HR'),
    (gen_random_uuid(), 'HR_WRITE',            'Edit HR',             'HR'),
    (gen_random_uuid(), 'STAFF_INVITE',        'Invite Staff',        'HR'),
    (gen_random_uuid(), 'ANALYTICS_OWN',       'Own Analytics',       'ANALYTICS'),
    (gen_random_uuid(), 'ANALYTICS_ALL',       'All Analytics',       'ANALYTICS'),
    (gen_random_uuid(), 'REPORTS_EXPORT',      'Export Reports',      'ANALYTICS'),
    (gen_random_uuid(), 'AI_COPILOT',          'AI Copilot',          'AI'),
    (gen_random_uuid(), 'ROLE_MANAGE',         'Manage Roles',        'ADMIN'),
    (gen_random_uuid(), 'USER_MANAGE',         'Manage Users',        'ADMIN'),
    (gen_random_uuid(), 'TENANT_CONFIG',       'Tenant Settings',     'ADMIN'),
    (gen_random_uuid(), 'ASSETS_MANAGE',       'Manage Assets',       'ADMIN')
ON CONFLICT (code) DO NOTHING;
